### PR TITLE
Use GitHub Actions for CI

### PR DESCRIPTION
**Pull request by jeddy3**
> Which issue, if any, is this issue related to?

Part of standardisation stream.

> Is there anything in the PR that needs further explanation?

I've connected Heroku to this repo, and setup automatic deployments on commits to master. Deployment was previously done within the `travis.yml`.

Heroku login details are now in the vault.

### CODE REVIEW

**Comment by jeddy3** [comment]
> Travis CI - Pull Request Expected — Waiting for status to be reported
Required

It looks like Travis is still firing. Does anyone have access to the Travis project to remove it?

**Comment by hudochenkov** [comment]
I removed Travis access to this repository, and enabled new CIs as requirement for PR merge.

**Comment by jeddy3** [comment]
> I removed Travis access to this repository, and enabled new CIs as requirement for PR merge.

Thank you. Was there any more residual Travis access for other stylelint repositories, or was this the last one?

**Comment by hudochenkov** [comment]
@jeddy3 there are some repositories left https://github.com/organizations/stylelint/settings/installations/158373

**Pull request merged**
